version: "3.3"

services:

  maildev:
    image: djfarrelly/maildev
    container_name: "maildev"
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "${SMTP_PORT}:25"
      - "${WEBMAIL_PORT}:80"

  phpdev:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: "phpdev"
    env_file: ./.env
    environment:
      TZ: "Europe/Zurich"
      SMTP_SERVER: "maildev"
      SMTP_PORT: ${SMTP_PORT}
      MAIL_FROM: "webdev@docker.local"
    volumes:
      - ./.docker/msmtprc:/etc/msmtprc:ro
      - ./code:/opt/code
    ports:
      - "${PHP_PORT}:8888"
    expose:
      - 9000
    links:
      - maildev:maildev
